### ISSUE TITLE
Regression on Multi-Schema Postgres DBs

### ISSUE THREAD

**Issue by ariel-codes** [lorint/brick#18]
Since at most `v1.0.176`, Rails throws an error during initialization when using The Brick. The error itself varies with version so may be caused by different issues. 

[will update later this week with more details and exact versions]

**Comment by lorint** [comment]
Cool to know -- appreciate this feedback.

I plan on releasing another update on Saturday or Sunday, and would want to include a fix for schema things if possible.

It may also affect **Oracle** and **Microsoft SQL Server** since those engines also offer schema support.  (Probably not a primary focus as these database adapters are now rarely used in Rails environments -- just wanted to put that note out there in hopes to loop in anyone using Brick with schemas on those database engines.)

**Comment by lorint** [comment]
Have tested out some Postgres scenarios with tables in various schemas, and have probably replicated the issue that you were seeing.  Have started to put together a fix, and plan on rolling it out around noon GMT tomorrow (Saturday the 6th).

Thanks for bringing this issue to my attention!

**Comment by lorint** [comment]
ok [ariel-codes](https://github.com/ariel-codes) -- Brick 1.0.214 has now shipped, and it includes a fix for issues with multi-schema Postgres databases.  Please let me know if this properly addresses your given use case.

To update an existing Rails app to use the latest version of **Brick**, run this:

```
bundle update brick
```

Thanks very much for reporting this issue!
